# Generated by Django 4.0.4 on 2022-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_alter_familiares_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name=10),
        ),
    ]
