# Generated by Django 4.0.4 on 2022-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_alter_familiares_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
